### ISSUE TITLE
Comment delimiter spans should be hidden in odoc's output

### ISSUE THREAD

**Issue by jonludlam** [ocaml/ocaml.org#1344]
Odoc produces output that should be cut-n-pasteable, and so in type definitions it wraps the text descriptions of fields and constructors in comment delimiters `(* *)`. This isn't intended to be _seen_ though, so we add the class `comment-delim` and hide these via this css (taken from `odoc.css`):

```css
/* Comment delimiters, hidden but accessible to screen readers and 
   selected for copy/pasting */

/* Taken from bootstrap */
/* See also https://stackoverflow.com/a/27769435/4220738 */
.comment-delim {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
```

See, for example, [Typedtree in ocaml-base-compiler](https://ocaml.org/p/ocaml-base-compiler/5.0.0/doc/Typedtree/index.html#type-pat_extra.Tpat_unpack)
